### ISSUE TITLE
Show OSM link for non OSM sources

### ISSUE THREAD

**Issue by planemad** [batpad/quick-geocode#3]
Use case: I want to see the location of the match from geonames to see what feature exists there on OSM https://batpad.github.io/quick-geocode/?name=Sokollu%20Mehmet%20Pa?a%20Mosque&city=Istanbul

cc @batpad

**Comment by batpad** [comment]
This should be fixed in https://github.com/batpad/quick-geocode/commit/6ae455a9e21d92a28b7d2e5d21f9f0a073bad22c . Let me know @planemad .
