### ISSUE TITLE
Show external search links

### ISSUE THREAD

**Issue by planemad** [batpad/quick-geocode#4]
If a place cannot be found on OSM, the next step is to do a web search on alternate sources. These are popular ones with links to a sample query `hilton, istanbul`
- [Google](https://www.google.com/#q=hilton%2C+istanbul)
- [Wikidata](https://www.wikidata.org/w/index.php?title=Special:Search&profile=default&fulltext=Search&search=hilton&searchToken=22p3iup23sh0p7na9lp2ic88g)

**Comment by batpad** [comment]
Added. Let me know if this works.

**Comment by planemad** [comment]
Thanks @batpad. The external links should be sufficient for just the original query instead of each geocoder result. We could have it at the bottom of the page, once we are done examining the geocoder results.

**Comment by batpad** [comment]
@planemad good point - didn't need to repeat the links in every row - this should be fixed now, please close if all looks good?

**Comment by planemad** [comment]
👯
